### ISSUE TITLE
Add "Routers" to manage Dovado Routers

### ISSUE THREAD

**Issue by marcoherbst** [EdgeCommander/edge-commander#11]

**Comment by ijunaid8989** [comment]
Just for my own information so I don't take a long road unknowingly: @marcoherbst 

The task is not only to create a report for adding few fields but to connect with Dovado router with its API to get the information of device as well, same as we are doing for NVR with ISAPI commands.

**Comment by ijunaid8989** [comment]
follow up: Report for CRUD ops has been added.

**Comment by ijunaid8989** [comment]
Router's report as has been added. its done.
