### ISSUE TITLE
RAID Commander

### ISSUE THREAD

**Issue by ijunaid8989** [EdgeCommander/edge-commander#147]
Show

- [ ]  All servers with a button to re-run a test for the RAID.
- [ ]  When last we check raid status.
- [ ]  Save status of for raid and show with some graphical representation using D3 or HighCharts
- [ ]  Give some handy commands, as See Media/smart warnings errors etc.

**Comment by marcoherbst** [comment]
@ijunaid8989 , aside from this task, are we happy that raid monitoring is running on all machines and you are being alerted as necessary? (firewall has not interfered with this, or anything else...)

**Comment by ijunaid8989** [comment]
@marcoherbst Yes its working and I am getting emails when it's necessary, 

Also, I am doing ssh to the server and then running the command with Adaptec as well as mega cli, to get the results. so Firewall has nothing to do with it
