### ISSUE TITLE
Make accessibility of own data after login.

### ISSUE THREAD

**Issue by Ali7862** [EdgeCommander/edge-commander#163]
We are saving Sims data against a single user so we will do these steps.
- [ ] Modify three scraper and save data with the relevant user id.
- [ ] Start scaper when adding or modify three user's account details.
- [ ] Add user id  in SIMs module (Display user's SIMs, Add user id on adding SIMs)

**Comment by marcoherbst** [comment]
@Ali7862 This is a strange issue. The items do not seem relevant to the topic. Some are complete. 

Clean this up, please.

**Comment by Ali7862** [comment]
It's done.
