### ISSUE TITLE
httpS add SSL

### ISSUE THREAD

**Issue by marcoherbst** [EdgeCommander/edge-commander#186]

**Comment by ijunaid8989** [comment]
I have just configured SSL through Heroku

https://www.app.edgecommander.com/users/sign_in
https://app.edgecommander.com/users/sign_in

Need to work on redirection now.

**Comment by ijunaid8989** [comment]
its done. 
SSLs are added to 
https://www.app.edgecommander.com
https://app.edgecommander.com
