### ISSUE TITLE
UX items v2

### ISSUE THREAD

**Issue by marcoherbst** [EdgeCommander/edge-commander#36]
- [x] x-axis give true dot spacing
- [ ]  Add status to NVR report, maybe also include last 24hrs in vizavil

**Comment by ijunaid8989** [comment]
- [x] I have changed the graph its way more clear than before at the moment.

![image](https://user-images.githubusercontent.com/13561999/31658379-457f04dc-b34a-11e7-862d-40b9b1148fe3.png)


- [ ] Adding 24 Hours status bar doesn't seem possible at the moment, how things are, So I am leaving that bit right now.

**Comment by marcoherbst** [comment]
I'll move NVR Status to a new issue
