### ISSUE TITLE
Show Missing Data on Graphs

### ISSUE THREAD

**Issue by marcoherbst** [EdgeCommander/edge-commander#394]
@Ali7862 I am not sure I ever really got this concept across to you. Here you can see what I was trying to describe for when we have no readings from a battery:

https://metricsgraphicsjs.org/examples.htm#data  (see "missing data range / points")

![image](https://user-images.githubusercontent.com/5648894/57015252-bcd49800-6c0b-11e9-869a-489176495e6c.png)

**Comment by Ali7862** [comment]
It's done.
