### ISSUE TITLE
Command 1: When Usage > 90% send email notification 

### ISSUE THREAD

**Issue by marcoherbst** [EdgeCommander/edge-commander#40]
We check usage each day. 
For each time SIM > 90%, send an email to user

**Comment by ijunaid8989** [comment]
All the backend work has been done and its working as well.

But only thing left is to add proper email template for the email.

**Comment by marcoherbst** [comment]
@ijunaid8989 and he can practice here :)

**Comment by Ali7862** [comment]
An email template has been added, with details of data usage.
