### ISSUE TITLE
Router added, screen does not update

### ISSUE THREAD

**Issue by marcoherbst** [EdgeCommander/edge-commander#47]
![image](https://user-images.githubusercontent.com/5648894/31810968-ac5334e4-b575-11e7-8b83-f1cf74cd609c.png)

**Comment by ijunaid8989** [comment]
it's done.
I have written a method for reloading the table with ajax, https://github.com/EdgeCommander/edge-commander/commit/0e1a143a3e34dcfa587d1aff61153f700bf09b1f#diff-82774658c2a137f927d40c521930979bL884
