### ISSUE TITLE
Add NVR using QR Code

### ISSUE THREAD

**Issue by marcoherbst** [EdgeCommander/edge-commander#52]
Scan the QR code to add the device. See if you can do this. You'll need a QR code reading API and will also need to access the USB camera via browser.

**Comment by Ali7862** [comment]
@marco
I have worked on "Add NVR using QR" and  Found the API for QR scanning by using internal or external Camera. but stuck off that point when I scan Hikvision NVR QR Code I get encrypted value. What do I do with this encrypted value?

**Comment by Ali7862** [comment]
It cannot be done, so we are closing this.
