### ISSUE TITLE
Migrate relevant features into Evercam Admin

### ISSUE THREAD

**Issue by marcoherbst** [EdgeCommander/edge-commander#553]
+ SMS
+ Messages
+ Batteries

**Comment by fateh-evercam** [comment]
### Done
https://app.edgecommander.com/ is de-commission.

**Comment by fateh-evercam** [comment]
### Done
https://app.edgecommander.com/ is decommissioned.

**Comment by fateh-evercam** [comment]
@azharmalik3 will remove the Domain and DB after verification.
