### ISSUE TITLE
Future of RAID notifications.

### ISSUE THREAD

**Issue by ijunaid8989** [EdgeCommander/edge-commander#557]
There is a hidden feature in Edge Commander, which is to send me an email alert about RAID disk failures.

Of course, we are not going to just lose it.
Either I will move it to evercam admin.
or it can work a separate application, a small repo to just check on the raid.

**Comment by fateh-evercam** [comment]
### Transfered
Transferred this last issue from the Edge Commander #557 to the Admin https://github.com/evercam/evercam-admin/issues/202
