### ISSUE TITLE
Add SMS Functionality

### ISSUE THREAD

**Issue by marcoherbst** [EdgeCommander/edge-commander#58]
Ability to send SMS & read SMS from https://www.nexmo.com/pricing
List all SMS received from  / sent to a SIM

https://github.com/KindyNowApp/ex_nexmo ?

**Comment by ijunaid8989** [comment]
If it's all about, just SMS, then I would *NOT* recommend adding that dependency in the project, It worth to make our own small module for this purpose, using HTTPoison, Documentation seems so simple.

**Comment by marcoherbst** [comment]
Acually, I couldn't get a number from Nexmo, so chances are we'll use AWS or Twilio

**Comment by marcoherbst** [comment]
@ijunaid8989 you could show Ali how to comment and close an issue please

**Comment by Ali7862** [comment]
It's done.
