### ISSUE TITLE
Branding - Favicon, App Logo etc.

### ISSUE THREAD

**Issue by marcoherbst** [EdgeCommander/edge-commander#72]
Ask me when you want to tackle this.

https://drive.google.com/a/evercam.io/file/d/1wHJf5xc9o1z35kEVqz7qZawlzL0i2lLL/view?usp=sharing

https://avatars0.githubusercontent.com/u/32387536?s=200&v=4
![image](https://user-images.githubusercontent.com/5648894/33935565-4e5f718c-dff4-11e7-9765-e744566bd4d7.png)

![image](https://user-images.githubusercontent.com/5648894/33935555-46adcdda-dff4-11e7-94b5-6a430eab2482.png)

**Comment by Ali7862** [comment]
It's done.
