### ISSUE TITLE
A lovely swagger API :)

### ISSUE THREAD

**Issue by marcoherbst** [EdgeCommander/edge-commander#75]
We discussed this for Evercam.
One of the reasons you're doing this is to learn how swagger (now OpenAPI) works and how it can be done really nicely...

The API endpoints will be api.edgecommander.com/v1/.... 

Think carefully about how you want them to look, this can easily be done badly.

**Comment by ijunaid8989** [comment]
This is not an API. it's an application which connecting all its method to itself. not serving as a third-party tool as well.

I don't see any need of Swagger for this. Unless we make it have one. 
e.g create user api keys, change the structure to separate usual methods and API endpoint  (for creating an NVR, Command, SITE, Router, SMS). Mostly swagger is a face to hidden skeletons, We already have an interface to all our methods. It will be a waste of time to make a separate interface to connect with it.

**Comment by marcoherbst** [comment]
@Ali7862 close this issue?

**Comment by Ali7862** [comment]
It's done.
